### ISSUE TITLE
sometimes the food dissapears

### ISSUE THREAD

**Issue by amapic** [AdnanZahid/SnakeGame#1]
Hi,
Thanks for you code.
Sometimes, the food disappears. Can you fix it ?

**Comment by AdnanZahid** [comment]
Hello,

Thank you for the message. I'll look into it. In the meanwhile, can you provide a video or photo to explain the problem better? That would help a lot in debugging and solving the issue faster.

**Comment by amapic** [comment]
Hello,
yes, ok, I will do it.
Thanks.

**Comment by amapic** [comment]
Hi,
Sorry I didn't manage to repeat the error.
Thanks for your help anyway.

**Comment by AdnanZahid** [comment]
Alright, thanks for dropping by. I'm closing this issue now.
